fixed sonar minor issues
hmcts/rd-user-profile-api pull request #772
Opened 2022-02-08 11:59 UTC by nayeemshaik-hmcts

### JIRA link (if applicable) ###
[RDCC-3462](https://tools.hmcts.net/jira/browse/RDCC-3462)

### Change description ###
Address remaining Sonar issues in Ref Data repos

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-02-08 13:37 UTC, AdilOoze approved these changes

2022-02-08 13:37 UTC, shreedhar-hmcts submitted a review, later dismissed

2022-02-08 13:55 UTC, SujeethKumarAri requested changes
@nayeemshaik-hmcts - still could see two minor smells https://sonarcloud.io/project/issues?id=RDUSERPROFILEAPI&pullRequest=772&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL. are we just fixing only major and critical?

2022-02-08 14:13 UTC, SujeethKumarAri approved these changes

2022-02-08 15:02 UTC, AdilOoze approved these changes

2022-02-10 11:03 UTC, SujeethKumarAri approved these changes

2022-02-10 12:25 UTC, shivajilokare approved these changes
looks good to me

2022-02-10 14:17 UTC, merged