User profile API to retrieve user profile details
hmcts/rd-user-profile-api pull request #927
Opened 2023-02-06 13:22 UTC by vasthav-patta

JIRA link
https://tools.hmcts.net/jira/browse/RDCC-6260 

Change description
 User Profile API to retrieve user profile details

Does this PR introduce a breaking change?

```
[ ] Yes
[ x] No
```

2023-02-07 13:58 UTC, rajkatla-hmcts requested changes

2023-02-07 13:58 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
> +        assertThat(Objects.requireNonNull(retrievedResource)
check the expected email address

2023-02-07 13:58 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/userprofileapi/integration/RetrieveUserProfileIntTest.java
> +        assertThat(Objects.requireNonNull(retrievedResource)
check the expected idam status

2023-02-07 15:53 UTC, rajkatla-hmcts submitted a review, later dismissed

2023-02-07 17:43 UTC, rajkatla-hmcts approved these changes

2023-02-08 12:57 UTC, sahitya-desireddy approved these changes

2023-02-21 10:37 UTC, merged